package com.bjming.crm.settings.mapper;

import com.bjming.crm.settings.domain.DicType;

import java.util.List;

public interface DicTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Sat Dec 05 21:52:44 CST 2020
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Sat Dec 05 21:52:44 CST 2020
     */
    int insert(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Sat Dec 05 21:52:44 CST 2020
     */
    int insertSelective(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Sat Dec 05 21:52:44 CST 2020
     */
    DicType selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Sat Dec 05 21:52:44 CST 2020
     */
    int updateByPrimaryKeySelective(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Sat Dec 05 21:52:44 CST 2020
     */
    int updateByPrimaryKey(DicType record);

    /**
     * 查询表中所有的数据字典类型
     *
     * @return
     */
    List<DicType> selectAllDicType();

    /**
     * 从实体类插入一条记录
     *
     * @return rows
     */
    int insertDicType(DicType dicType);

    /**
     * 根据主键字段查询字典类型
     *
     * @param code 编码
     * @return 实体类对象, 不存在返回null
     */
    DicType selectDicTypeByCode(String code);

    /**
     * 根据主键从数据中删除多条记录
     *
     * @param codes code1, code2
     * @return rows
     */
    int deleteDicTypeByCodes(String[] codes);

    /**
     * 从实体类对象中更新一条记录
     *
     * @param dicType 实体类对象
     * @return rows
     */
    int updateDicType(DicType dicType);
}