package com.bjming.crm.settings.mapper;

import com.bjming.crm.settings.domain.DicValue;

import java.util.List;

public interface DicValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sat Dec 05 21:52:44 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sat Dec 05 21:52:44 CST 2020
     */
    int insert(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sat Dec 05 21:52:44 CST 2020
     */
    int insertSelective(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sat Dec 05 21:52:44 CST 2020
     */
    DicValue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sat Dec 05 21:52:44 CST 2020
     */
    int updateByPrimaryKeySelective(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sat Dec 05 21:52:44 CST 2020
     */
    int updateByPrimaryKey(DicValue record);

    //*******************************************************

    /**
     * 根据外键字段, typeCode来查询多条数据字典记录
     *
     * @return
     */
    List<DicValue> selectDicValuesByTypeCode(String typeCode);
}