package com.bjming.crm.settings.mapper;

import com.bjming.crm.settings.domain.User;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Wed Dec 02 15:49:48 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Wed Dec 02 15:49:48 CST 2020
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Wed Dec 02 15:49:48 CST 2020
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Wed Dec 02 15:49:48 CST 2020
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Wed Dec 02 15:49:48 CST 2020
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Wed Dec 02 15:49:48 CST 2020
     */
    int updateByPrimaryKey(User record);

    /**
     * 根据用户名密码查询用户, 密码使用MD5格式密文
     * @param map loginAct , loginPwd
     * @return user
     */
    User selectUserByActAndPwd(Map<String, Object> map);

    /**
     * 查询表中所有可用的用户
     *      未被锁定, 且在有效时间内
     * @param expireTime 有效时间
     * @param notLockState 未被锁定的标记
     */
    List<User> selectAllAvailableUsers(@Param("expireTime") String expireTime, @Param("notLockState") String notLockState);
}